### ISSUE TITLE
Gottesdienstplan hinlöten

### ISSUE THREAD

**Issue by rincewind** [rincewind/kioskbackend#11]
Von dort.

https://www.kirche-froemern.de/gruppen-angebote/gottesdienste

**Comment by rincewind** [comment]
Gibt's jetzt. Wird aber sicherlich kaputt gehen, wenn da Jahreszahlen dazu kommen zum Jahresende oder sich jemand entscheidet die Monate anders abzukürzen oder sowas.

Korrekte Lösung wäre auch hier, das strukturiert zu erfassen und daraus dann alle Stellen zu speisen, die den Gottesdienstplan brauchen. Aber das ist ein zu dickes Brett und so geht's ja auch. Hinweis an mich, wenn's klemmt (evtl. bekomme ich das auch automatisch mitgeteilt. Wenn es so richtig kaputt ist.)

z.K. @Carpetcrawlwer

**Comment by Carpetcrawlwer** [comment]
das wäre dann sonst n Thema für Gisbert / Barbara Stein-Rossberg
Freundliche Grüße

*Sebastian Richter* (er/ihn)
Vorsitzender

*Neue Mailadresse: Dienstliche Themen bitte nur noch
an ***@***.***
***@***.***> oder ***@***.***
***@***.***>.*


Am Di., 17. Okt. 2023 um 16:44 Uhr schrieb Peter Quade <
***@***.***>:
