### ISSUE TITLE
Lösung für Ein-Ausschalten installieren

### ISSUE THREAD

**Issue by Carpetcrawlwer** [rincewind/kioskbackend#20]
Marten fragte danach... TV geht nach 4 Stunden immer wieder aus und muss manuell eingeschaltet werden - macht er's nicht, bleibt er aus...
bin - wenn wieder fit - Donnerstag am Morgen (so gg 10h) im Gemeindeschafts-Haus. Kann ich da schon was berichten oder brauchst Du ne Info, die ich dann besorgen könnte?

**Comment by rincewind** [comment]
Alle halbe Stunde wird nun geschaut, ob es Sinn macht, dass der Fernseher an ist. Und dann der Fernseher entsprechend aufgeweckt oder ins standby geschickt.

Der Fernseher ist sinnvoll an, wenn gerade ein Event läuft, wenn innerhalb der nächsten Stunde einer anfängt oder wenn innerhalb der letzten Stunde einer endete. 

Bitte mal beobachten, wie sich das verhält und ob sich das verhält.

**Comment by Carpetcrawlwer** [comment]
Geil.
Und das klappt mit dem TV im Eingang ?

mobil gesendet

Peter Quade ***@***.***> schrieb am Do., 2. Nov. 2023, 01:10:

**Comment by rincewind** [comment]
Scheint erstmal zu klappen so. Manuelle Ein-/Aus Zeiten für so GH-Dankes-Brunch-Geschichten müsste noch dabei.

**Comment by Carpetcrawlwer** [comment]
nice.
was heißt "müssten" ? :D
Freundliche Grüße

*Sebastian Richter* (er/ihn)


Am Mo., 6. Nov. 2023 um 13:37 Uhr schrieb Peter Quade <
***@***.***>:

**Comment by rincewind** [comment]
Siehe https://github.com/rincewind/kioskbackend/issues/21
