### ISSUE TITLE
Funktionieren PDF und Bilder?

### ISSUE THREAD

**Issue by Carpetcrawlwer** [rincewind/kioskbackend#5]

**Comment by rincewind** [comment]
Aktuell sind Bilder vorgesehen. 

PDFs muss ich mal schauen wie der arme kleinen Raspi reagiert. Schöner wäre aber, wenn man Pixel draus macht. Das kann evtl. die Wartungsklappe übernehmen.

Also aus dem Bauch raus keine PDFs. Aber evtl. kann ich die beim Hochladen konvertieren.

**Comment by Carpetcrawlwer** [comment]
ok :)
Freundliche Grüße

*Sebastian Richter* (er/ihn)
Vorsitzender

*Neue Mailadresse: Dienstliche Themen bitte nur noch
an ***@***.***
***@***.***> oder ***@***.***
***@***.***>.*


Am Sa., 14. Okt. 2023 um 12:50 Uhr schrieb Peter Quade <
***@***.***>:
